# Setup
title: Elie's Rust Notes.
tagline: "Elie's Rust Notes"
baseurl: ""
paginate: 5
permalink: pretty

# About/contact
author:
  name: Elie Maatouk
  email: elie90@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version: 1.1.0
